services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: progree
      POSTGRES_PASSWORD: aarjubasnet@2004
      POSTGRES_DB: progree
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
